"""create Priority table

Revision ID: 2fd7fe057824
Revises: edbcd2d86961
Create Date: 2021-06-24 10:54:44.126353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd7fe057824'
down_revision = 'edbcd2d86961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trashed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tasks', schema=None) as batch_op:
        batch_op.drop_column('trashed')

    # ### end Alembic commands ###
