"""change Project model pk to name

Revision ID: 39917c13c46e
Revises: 8655de4746bd
Create Date: 2021-05-28 17:13:26.853037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39917c13c46e'
down_revision = '8655de4746bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('descriptions', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Projects_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Projects_name'))

    op.drop_table('Projects')
    # ### end Alembic commands ###
