"""v2

Revision ID: 5ab39c9e4d5c
Revises: 6b20396420cb
Create Date: 2021-05-28 20:39:55.201808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab39c9e4d5c'
down_revision = '6b20396420cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_avatar_url'), ['avatar_url'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_avatar_url'))

    # ### end Alembic commands ###
