"""create Priority table

Revision ID: 9d36cc3772fe
Revises: 
Create Date: 2021-06-18 09:43:14.113705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d36cc3772fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('Tasks')
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index('ix_Projects_descriptions')
        batch_op.drop_index('ix_Projects_name')

    op.drop_table('Projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descriptions', sa.VARCHAR(length=75), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index('ix_Projects_name', ['name'], unique=False)
        batch_op.create_index('ix_Projects_descriptions', ['descriptions'], unique=False)

    op.create_table('Tasks',
    sa.Column('task_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(length=50), nullable=False),
    sa.Column('description', sa.TEXT(length=255), nullable=False),
    sa.Column('user_id', sa.TEXT(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.drop_table('Priorities')
    # ### end Alembic commands ###
