"""create Priority table

Revision ID: a1a613d4ba6e
Revises: 1735a822a0b9
Create Date: 2021-07-09 07:38:23.876807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a613d4ba6e'
down_revision = '1735a822a0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trashed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_column('trashed')

    # ### end Alembic commands ###
