"""add Project model

Revision ID: b20e89d9f14b
Revises: 4ae6a6a77a1d
Create Date: 2021-05-28 16:49:13.904548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20e89d9f14b'
down_revision = '4ae6a6a77a1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('descriptions', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Projects_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Projects_name'))
        batch_op.drop_index(batch_op.f('ix_Projects_id'))

    op.drop_table('Projects')
    # ### end Alembic commands ###
