"""v2

Revision ID: bb756c135838
Revises: 
Create Date: 2021-06-03 11:01:11.795031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb756c135838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index('ix_Projects_descriptions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index('ix_Projects_descriptions', ['descriptions'], unique=False)

    # ### end Alembic commands ###
