"""v2

Revision ID: c242a46ef62c
Revises: bb756c135838
Create Date: 2021-06-03 11:01:31.319266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c242a46ef62c'
down_revision = 'bb756c135838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Projects_descriptions'), ['descriptions'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Projects_descriptions'))

    # ### end Alembic commands ###
