"""create Priority table

Revision ID: edbcd2d86961
Revises: 9d36cc3772fe
Create Date: 2021-06-18 09:44:15.846694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbcd2d86961'
down_revision = '9d36cc3772fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['Priorities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tasks')
    # ### end Alembic commands ###
