"""change Project model pk to name

Revision ID: fb323c91a27a
Revises: 39917c13c46e
Create Date: 2021-05-28 17:15:49.780753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb323c91a27a'
down_revision = '39917c13c46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Projects_descriptions'), ['descriptions'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Projects_descriptions'))

    # ### end Alembic commands ###
